service: ssrserverless-angular

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  timeout: 30
  stage: production
  region: eu-west-3

package:
  patterns:
    - '!src/**'
    - '!node_modules/**'
    - '!firebug-lite/**'
    - '!e2e/**'
    - '!coverage/**'
    - '!.angular/**'
    - '!.idea/**'
    - '!.vscode/**'
    - node_modules/aws-serverless-express/**
    - node_modules/@vendia/serverless-express/**
    - node_modules/binary-case/**
    - node_modules/type-is/**
    - node_modules/media-typer/**
    - node_modules/mime-types/**
    - node_modules/mime-db/**

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  api:
    handler: lambda.ssrserverless
    events:
      - http: ANY /{proxy+}
      - http: ANY /

plugins:
  - serverless-plugin-simulate
  - serverless-offline
